// Code generated by sqlc. DO NOT EDIT.

package db1

import (
	"database/sql"
)

type Author struct {
	ID   int64
	Name string
	Bio  string
	Uid  sql.NullInt64
}

type User struct {
	Userid   int64
	Username string
	Pass     string
}
